<?php


namespace MichalWolinski\Repository\Tests;


use Illuminate\Contracts\Console\Kernel;

/**
 * Class TestCase
 * @package MichalWolinski\Repository\Tests
 */
class TestCase extends \PHPUnit\Framework\TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}